### ISSUE TITLE
Content-Type of deployed S3 files is not correct

### ISSUE THREAD

**Issue by cch1** [pjstadig/lein-maven-s3-wagon#2]
We have run into an issue with the lein-ancient plugin not working with dependencies deployed by lein-maven-s3-wagon.  Specifically lein-ancient complains that the `maven-metadata.xml` files do not have the correct HTTP Content-Type.  Sometimes they are `application/octet-stream` and sometimes they are `text/plain` -but never do they seem to be `application/xml` or `text/xml` which are the appropriate choices.

By manually correcting the Content-Type of the deployed resource, we are able to restore the lein-ancient functionality, but that's not a suitable long-term solution. 

Please add functionality to set the Content-Type (and perhaps other HTTP metadata?) on deployed S3 resources.

Reference: https://github.com/xsc/lein-ancient/issues/43

**Comment by pjstadig** [comment]
This project is just a thin wrapper around my fork of maven-s3-wagon (https://github.com/pjstadig/maven-s3-wagon), and I'm guessing that this issue would be a problem with that library.

Would you mind moving the issue over there?

**Comment by cch1** [comment]
I don't think issues are enabled for https://github.com/pjstadig/maven-s3-wagon.

**Comment by pjstadig** [comment]
You're right.  Sorry. I turned them on.
